//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface ActivityManagerDebugRecentActionItem : NSObject
{
    NSDate *_when;
    NSString *_str;
}

@property(copy) NSString *str; // @synthesize str=_str;
@property(copy) NSDate *when; // @synthesize when=_when;
- (void).cxx_destruct;
- (id)initWithString:(id)arg1;

@end

