//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXPCListenerDelegate.h"
#import "UAResumableActivitiesAdministrativeProtocol.h"
#import "UAResumableActivitiesSysdiagnoseSupportProtocol.h"
#import "UAUserActivityDebugLoggingProtocol.h"

@class NSString, NSXPCListener, SharingBTLESuggestedItem, UAActivityReplay, UACornerActionManager, UANetworkReplayRendevousHandler, UAPingController;

@interface ActivityManagerDebuggingManager : NSObject <NSXPCListenerDelegate, UAResumableActivitiesAdministrativeProtocol, UAResumableActivitiesSysdiagnoseSupportProtocol, UAUserActivityDebugLoggingProtocol>
{
    BOOL _supportNetworkPeers;
    BOOL _disableAdminEntitlmentChecking;
    UACornerActionManager *manager;
    SharingBTLESuggestedItem *fakeBTLEInjectedItem;
    NSXPCListener *listener;
    UAActivityReplay *_replayManager;
    UAPingController *_pingController;
    UANetworkReplayRendevousHandler *_networkConnectionHandler;
    unsigned long long _recentActionsStateHandler;
    struct timeval _ignoredRTimeVal;
}

+ (id)actionStrs:(long long)arg1 maximumInternal:(double)arg2 clear:(BOOL)arg3;
+ (void)appendRecentAction:(id)arg1;
+ (void)log:(int)arg1 format:(id)arg2;
+ (void)log:(int)arg1 format:(id)arg2 args:(struct __va_list_tag [1])arg3;
@property unsigned long long recentActionsStateHandler; // @synthesize recentActionsStateHandler=_recentActionsStateHandler;
@property(readonly) struct timeval ignoredRTimeVal; // @synthesize ignoredRTimeVal=_ignoredRTimeVal;
@property(retain) UANetworkReplayRendevousHandler *networkConnectionHandler; // @synthesize networkConnectionHandler=_networkConnectionHandler;
@property(retain) UAPingController *pingController; // @synthesize pingController=_pingController;
@property(retain) UAActivityReplay *replayManager; // @synthesize replayManager=_replayManager;
@property BOOL disableAdminEntitlmentChecking; // @synthesize disableAdminEntitlmentChecking=_disableAdminEntitlmentChecking;
@property(retain) NSXPCListener *listener; // @synthesize listener;
@property(retain) SharingBTLESuggestedItem *fakeBTLEInjectedItem; // @synthesize fakeBTLEInjectedItem;
@property(retain) UACornerActionManager *manager; // @synthesize manager;
- (void).cxx_destruct;
- (void)doGetSFActivityAdvertisement:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doGetLoggingFileForClient:(id)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)doSetLocalPasteboardReflection:(BOOL)arg1;
- (void)doSetRemotePasteboardAvalible:(BOOL)arg1;
- (void)doSetDefaults:(id)arg1 value:(id)arg2;
- (void)doCopyDefaults:(BOOL)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doReplayCommands:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doGetSysdiagnoseStringsIncludingPrivateData:(BOOL)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)getCurrentPeersAndClear:(BOOL)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)stopAdvertisingPing;
- (void)startAdvertisingPingWithTimeInterval:(double)arg1;
- (void)doSetupRendevous:(id)arg1 domain:(id)arg2 activate:(BOOL)arg3;
- (void)doSetupNetworkedPairs:(id)arg1 port:(long long)arg2;
- (void)doBroadcastPing:(CDUnknownBlockType)arg1;
- (void)doDidSaveDelegate:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doWillSaveDelegate:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doTerminateServer;
- (void)doInjectBTLE:(id)arg1 type:(unsigned long long)arg2 identifier:(id)arg3 title:(id)arg4 activityPayload:(id)arg5 frameworkPayload:(id)arg6 payloadDelay:(double)arg7;
- (void)doGetCurrentAdvertisedItemUUID:(CDUnknownBlockType)arg1;
- (void)doCopySimulatorStatusString:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doCopyRecentActions:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doCopyStatusString:(id)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)doCopyDynamicUserActivitiesString:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doCopyDebuggingInfo:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doCopyEnabledUUIDsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)doCopyAdvertisedUUIDWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)doCopyAllUUIDsOfType:(unsigned long long)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)doFindMatchingUserActivityForString:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)doSetDebugOption:(id)arg1 value:(id)arg2;
- (void)doNOP:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)receivePing:(id)arg1;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (double)currentPerfTime;
- (id)perfSummaryString;
@property BOOL supportNetworkPeers; // @synthesize supportNetworkPeers=_supportNetworkPeers;
- (void)setDebugging:(BOOL)arg1;
- (void)resume;
- (void)suspend;
- (id)initWithManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

