//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@class NSString;

@interface AWDHandoffRemotePasteboardWasRequested : PBCodable <NSCopying>
{
    long long _errorCode;
    long long _numberOfItems;
    unsigned long long _payloadSize;
    unsigned long long _payloadXferSpeed;
    unsigned long long _payloadXferTime;
    unsigned long long _streamDataSize;
    unsigned long long _streamDataXferSpeed;
    unsigned long long _streamDataXferTime;
    unsigned long long _streamOpenTime;
    unsigned long long _timestamp;
    unsigned long long _totalTime;
    long long _underlyingErrorCode;
    NSString *_remoteDeviceType;
    BOOL _cancelled;
    BOOL _isAsyncTransfer;
    BOOL _isFileCopy;
    BOOL _usedStreams;
    struct {
        unsigned int errorCode:1;
        unsigned int numberOfItems:1;
        unsigned int payloadSize:1;
        unsigned int payloadXferSpeed:1;
        unsigned int payloadXferTime:1;
        unsigned int streamDataSize:1;
        unsigned int streamDataXferSpeed:1;
        unsigned int streamDataXferTime:1;
        unsigned int streamOpenTime:1;
        unsigned int timestamp:1;
        unsigned int totalTime:1;
        unsigned int underlyingErrorCode:1;
        unsigned int cancelled:1;
        unsigned int isAsyncTransfer:1;
        unsigned int isFileCopy:1;
        unsigned int usedStreams:1;
    } _has;
}

@property(retain, nonatomic) NSString *remoteDeviceType; // @synthesize remoteDeviceType=_remoteDeviceType;
@property(nonatomic) BOOL isAsyncTransfer; // @synthesize isAsyncTransfer=_isAsyncTransfer;
@property(nonatomic) BOOL isFileCopy; // @synthesize isFileCopy=_isFileCopy;
@property(nonatomic) long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(nonatomic) long long underlyingErrorCode; // @synthesize underlyingErrorCode=_underlyingErrorCode;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(nonatomic) unsigned long long totalTime; // @synthesize totalTime=_totalTime;
@property(nonatomic) unsigned long long streamDataXferSpeed; // @synthesize streamDataXferSpeed=_streamDataXferSpeed;
@property(nonatomic) unsigned long long streamDataXferTime; // @synthesize streamDataXferTime=_streamDataXferTime;
@property(nonatomic) unsigned long long streamDataSize; // @synthesize streamDataSize=_streamDataSize;
@property(nonatomic) unsigned long long streamOpenTime; // @synthesize streamOpenTime=_streamOpenTime;
@property(nonatomic) BOOL usedStreams; // @synthesize usedStreams=_usedStreams;
@property(nonatomic) unsigned long long payloadXferSpeed; // @synthesize payloadXferSpeed=_payloadXferSpeed;
@property(nonatomic) unsigned long long payloadXferTime; // @synthesize payloadXferTime=_payloadXferTime;
@property(nonatomic) unsigned long long payloadSize; // @synthesize payloadSize=_payloadSize;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) BOOL hasRemoteDeviceType;
@property(nonatomic) BOOL hasIsAsyncTransfer;
@property(nonatomic) BOOL hasIsFileCopy;
@property(nonatomic) BOOL hasNumberOfItems;
@property(nonatomic) BOOL hasUnderlyingErrorCode;
@property(nonatomic) BOOL hasErrorCode;
@property(nonatomic) BOOL hasCancelled;
@property(nonatomic) BOOL hasTotalTime;
@property(nonatomic) BOOL hasStreamDataXferSpeed;
@property(nonatomic) BOOL hasStreamDataXferTime;
@property(nonatomic) BOOL hasStreamDataSize;
@property(nonatomic) BOOL hasStreamOpenTime;
@property(nonatomic) BOOL hasUsedStreams;
@property(nonatomic) BOOL hasPayloadXferSpeed;
@property(nonatomic) BOOL hasPayloadXferTime;
@property(nonatomic) BOOL hasPayloadSize;
@property(nonatomic) BOOL hasTimestamp;

@end

