//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@interface AWDHandoffRemotePasteboardTypeInfoRequested : PBCodable <NSCopying>
{
    long long _errorCode;
    unsigned long long _payloadSize;
    unsigned long long _payloadXferTime;
    unsigned long long _timestamp;
    struct {
        unsigned int errorCode:1;
        unsigned int payloadSize:1;
        unsigned int payloadXferTime:1;
        unsigned int timestamp:1;
    } _has;
}

@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) unsigned long long payloadXferTime; // @synthesize payloadXferTime=_payloadXferTime;
@property(nonatomic) unsigned long long payloadSize; // @synthesize payloadSize=_payloadSize;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (BOOL)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) BOOL hasErrorCode;
@property(nonatomic) BOOL hasPayloadXferTime;
@property(nonatomic) BOOL hasPayloadSize;
@property(nonatomic) BOOL hasTimestamp;

@end

