//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSSet, NSString, NSUUID, SFActivityAdvertiser, SFPeerDevice;

@protocol SFActivityAdvertiserDelegate <NSObject>
- (void)activityAdvertiser:(SFActivityAdvertiser *)arg1 activityPayloadForAdvertisementPayload:(NSData *)arg2 command:(NSString *)arg3 requestedByDevice:(SFPeerDevice *)arg4 withCompletionHandler:(void (^)(NSUUID *, NSData *, NSError *))arg5;

@optional
- (void)activityAdvertiser:(SFActivityAdvertiser *)arg1 didSendPayloadForActivityIdentifier:(NSUUID *)arg2 toDevice:(SFPeerDevice *)arg3 error:(NSError *)arg4;
- (void)activityAdvertiser:(SFActivityAdvertiser *)arg1 activityPayloadForAdvertisementPayload:(NSData *)arg2 requestedByDevice:(SFPeerDevice *)arg3 withCompletionHandler:(void (^)(NSUUID *, NSData *, NSError *))arg4;
- (void)activityAdvertiser:(SFActivityAdvertiser *)arg1 pairedDevicesChangedNotification:(NSSet *)arg2;
@end

