//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSData, NSDate, NSDictionary, NSUUID;

@interface SharingBTLEAdvertisementPayload : NSObject <NSCopying>
{
    struct {
        unsigned char hashedAdvertisementBytes[7];
        unsigned char optionBits;
        unsigned char timeOffset;
    } _bytes;
    NSUUID *_activityUUID;
    NSDate *_epochEnd;
    NSDictionary *_options;
    NSDate *_when;
    NSDate *_epochStart;
}

+ (id)dateEpochStart:(id)arg1;
@property(copy) NSDate *epochStart; // @synthesize epochStart=_epochStart;
@property(copy) NSDate *when; // @synthesize when=_when;
@property(copy) NSDictionary *options; // @synthesize options=_options;
@property(readonly, copy) NSUUID *activityUUID; // @synthesize activityUUID=_activityUUID;
- (void).cxx_destruct;
@property(readonly, copy) NSDate *epochEnd; // @synthesize epochEnd=_epochEnd;
- (id)now;
@property(readonly, copy) NSDate *validUntil; // @dynamic validUntil;
@property(readonly, copy) NSDate *currentUntil; // @dynamic currentUntil;
@property(readonly, copy) NSDate *time; // @dynamic time;
- (id)description;
- (BOOL)matchesItem:(id)arg1;
- (BOOL)isEqualHashedPayloadBytes:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) int advertisementKind; // @dynamic advertisementKind;
- (id)advertisementPayload;
@property(readonly) BOOL containsPasteboard;
- (BOOL)compareOptionBits:(unsigned char)arg1;
@property unsigned char optionBits;
@property unsigned char timeOffset; // @dynamic timeOffset;
@property(getter=isCurrent) BOOL current;
@property(copy) NSData *payloadBytes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAdvertisedBytes:(id)arg1;
- (id)initWithAdvertisedBytes:(id)arg1 options:(id)arg2;
- (id)initWithSFActivityAdvertisement:(id)arg1;
- (id)initWithType:(unsigned long long)arg1 string:(id)arg2 dynamicType:(id)arg3 teamID:(id)arg4 webpageURL:(id)arg5 options:(id)arg6 isCurrent:(BOOL)arg7 when:(id)arg8;
- (id)initWithType:(unsigned long long)arg1 string:(id)arg2 dynamicType:(id)arg3 teamID:(id)arg4 webpageURL:(id)arg5 options:(id)arg6 isCurrent:(BOOL)arg7 when:(id)arg8 versionFlags:(unsigned char)arg9;
- (id)initWithItem:(id)arg1 isCurrent:(BOOL)arg2 when:(id)arg3;
- (id)initWithItem:(id)arg1 isCurrent:(BOOL)arg2 when:(id)arg3 versionFlags:(unsigned char)arg4;

@end

