//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSSet, NSString, UACornerActionManager;

@protocol UAActivityNotifierProtocol
@property(copy) NSSet *notifiedItems;
- (id)initWithManager:(UACornerActionManager *)arg1 name:(NSString *)arg2;
@end

