//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

@class NSArray;

@interface UAAdvertiser : UACornerActionManagerHandler
{
}

- (id)statusString;
- (BOOL)terminate;
- (BOOL)okToSuspendAdvertising;
@property(readonly, copy) NSArray *advertisingItems;
@property(copy) NSArray *advertisableItems; // @dynamic advertisableItems;
@property(readonly) BOOL advertising;
- (BOOL)updateItem:(id)arg1;
- (id)initWithManager:(id)arg1 name:(id)arg2;

@end

