//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValue.h"

@interface UAAuditToken : NSValue
{
    CDStruct_4c969caf _auditTokenValue;
}

@property(readonly) CDStruct_4c969caf auditTokenValue; // @synthesize auditTokenValue=_auditTokenValue;
- (id)debugDescription;
- (id)description;
- (const char *)objCType;
- (void)getValue:(void *)arg1;
@property(readonly, getter=isSandboxed) BOOL sandboxed; // @dynamic sandboxed;
@property(readonly) int asid; // @dynamic asid;
@property(readonly) unsigned int rgid; // @dynamic rgid;
@property(readonly) unsigned int egid; // @dynamic egid;
@property(readonly) unsigned int ruid; // @dynamic ruid;
@property(readonly) unsigned int euid; // @dynamic euid;
@property(readonly) int pidVersion; // @dynamic pidVersion;
@property(readonly) int pid; // @dynamic pid;
- (id)initWithAuditToken:(CDStruct_4c969caf)arg1;

@end

