//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

#import "NSXPCListenerDelegate.h"

@class NSString, NSXPCListener;

@interface UABestAppSuggestionController : UACornerActionManagerHandler <NSXPCListenerDelegate>
{
    BOOL _disableEntitlementsCheck;
    NSXPCListener *_bestAppsListener;
}

@property(retain) NSXPCListener *bestAppsListener; // @synthesize bestAppsListener=_bestAppsListener;
@property BOOL disableEntitlementsCheck; // @synthesize disableEntitlementsCheck=_disableEntitlementsCheck;
- (void).cxx_destruct;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (BOOL)terminate;
- (BOOL)resume;
- (BOOL)suspend;
- (id)initWithManager:(id)arg1 name:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

