//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAActivityNotifier.h"

#import "UABestAppSuggestionManagerProtocol.h"

@class NSDate, NSMutableDictionary, NSString, NSUUID, NSXPCConnection, UADispatchScheduler;

@interface UABestAppSuggestionNotifier : UAActivityNotifier <UABestAppSuggestionManagerProtocol>
{
    BOOL _wantsBestAppChangedNotifications;
    NSXPCConnection *_connection;
    NSMutableDictionary *_supressedUntil;
    UADispatchScheduler *_scheduler;
    NSMutableDictionary *_possibleItems;
    NSUUID *_lastItemUUID;
    NSDate *_lastItemWhen;
    NSString *_lastItemStr;
}

@property(copy) NSString *lastItemStr; // @synthesize lastItemStr=_lastItemStr;
@property(copy) NSDate *lastItemWhen; // @synthesize lastItemWhen=_lastItemWhen;
@property(copy) NSUUID *lastItemUUID; // @synthesize lastItemUUID=_lastItemUUID;
@property(retain) NSMutableDictionary *possibleItems; // @synthesize possibleItems=_possibleItems;
@property(retain) UADispatchScheduler *scheduler; // @synthesize scheduler=_scheduler;
@property(retain) NSMutableDictionary *supressedUntil; // @synthesize supressedUntil=_supressedUntil;
@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)doQueueFetchOfPayloadForBestAppSuggestion:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doUnregisterForBestAppChangeNotification;
- (void)doRegisterForBestAppChangeNotification;
- (void)doLaunchFollowUp:(id)arg1 interactionType:(unsigned long long)arg2 cancelled:(BOOL)arg3;
- (void)doRemoveBestAppSuggestion:(id)arg1 options:(id)arg2;
- (void)doDetermineBestAppSuggestions:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doDetermineBestAppSuggestionWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)doStartBestAppSuggestion:(double)arg1;
- (void)doConnected;
- (id)statusString;
- (BOOL)terminate;
- (BOOL)resume;
- (BOOL)suspend;
- (BOOL)active;
- (void)update;
- (void)notifyBestAppChanged:(id)arg1 atTime:(id)arg2;
- (id)bestCornerItemFromItems:(id)arg1;
- (id)userActivityInfoForUUID:(id)arg1;
- (void)setItems:(id)arg1;
- (id)items;
@property BOOL wantsBestAppChangedNotifications; // @synthesize wantsBestAppChangedNotifications=_wantsBestAppChangedNotifications;
- (id)initWithManager:(id)arg1 connection:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

