//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSUUID;

@interface UABestAppUserActivityInfoSuppressionRecord : NSObject
{
    NSUUID *_itemUUID;
    NSDate *_hardSupressUntil;
    NSDate *_supressUntil;
    NSDate *_lastInterestingTime;
}

@property(copy) NSDate *lastInterestingTime; // @synthesize lastInterestingTime=_lastInterestingTime;
@property(copy) NSDate *supressUntil; // @synthesize supressUntil=_supressUntil;
@property(copy) NSDate *hardSupressUntil; // @synthesize hardSupressUntil=_hardSupressUntil;
@property(copy) NSUUID *itemUUID; // @synthesize itemUUID=_itemUUID;
- (void).cxx_destruct;
- (id)description;

@end

