//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

@interface UAClientController : UACornerActionManagerHandler
{
}

- (id)recentEligibleItemsInOrder:(double)arg1;
- (id)eligibleAdvertiseableItemsInOrder;
- (id)userActivityInfoForUUID:(id)arg1;
- (id)items;
- (id)initWithManager:(id)arg1 name:(id)arg2;

@end

