//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSUUID, UACornerActionManager;

@interface UACornerActionManagerHandler : NSObject
{
    BOOL _suspended;
    BOOL _terminated;
    NSUUID *_uuid;
    UACornerActionManager *_manager;
    NSString *_name;
    long long _priority;
}

@property(readonly) BOOL terminated; // @synthesize terminated=_terminated;
@property(readonly) long long priority; // @synthesize priority=_priority;
@property(copy) NSString *name; // @synthesize name=_name;
@property(readonly, retain) UACornerActionManager *manager; // @synthesize manager=_manager;
@property(readonly, retain) NSUUID *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (id)statusString;
- (BOOL)terminate;
- (BOOL)resume;
- (BOOL)suspend;
@property BOOL suspended;
@property(readonly) BOOL active;
- (id)initWithManager:(id)arg1 name:(id)arg2;

@end

