//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol UACornerActionManagerDebugInterface
- (void)updateUserActiveState:(BOOL)arg1;
- (void)updateScreenDimStateState:(BOOL)arg1;
- (void)updateScreenSaverActive:(BOOL)arg1;
@end

