//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAAdvertisableItem.h"

@interface UADebugAdvertisableItem : UAAdvertisableItem
{
    unsigned long long _debugType;
}

@property unsigned long long debugType; // @synthesize debugType=_debugType;
- (id)advertisingBytes;
- (id)initWithType:(unsigned long long)arg1 manager:(id)arg2;

@end

