//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AWDServerConnection;

@interface UADiagnosticManager : NSObject
{
    AWDServerConnection *_serverConn;
}

+ (id)sharedManager;
@property(retain, nonatomic) AWDServerConnection *serverConn; // @synthesize serverConn=_serverConn;
- (void).cxx_destruct;
- (unsigned long long)roundNum:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)submitLocalPasteboardInfoWasCleared;
- (void)submitRemotePasteboardBecameUnavailable:(int)arg1;
- (void)submitRemotePasteboardBecameAvailable;
- (void)submitRemotePasteboardTypeInfoRequested:(id)arg1;
- (void)submitDidSendLocalPasteboard:(id)arg1;
- (void)submitRemotePasteboardWasRequested:(id)arg1;
- (id)firstPartyActivityTypeOrUnknown:(id)arg1;
- (void)submitUserActivityWasContinuedInfo:(id)arg1;
- (void)submitUserActivityWasSuggestedInfo:(id)arg1;
- (void)submitUserActivityWasDiscovered:(id)arg1;
- (void)submitUserActivityBecameCurrent:(id)arg1 withToken:(const CDStruct_4c969caf *)arg2;
- (id)init;

@end

