//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString;

@interface UADispatchScheduler : NSObject
{
    double _frequency;
    unsigned long long _runCount;
    unsigned long long _nextTime;
    NSObject<OS_dispatch_source> *_source;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_group> *_executingGroup;
    NSString *_name;
    CDUnknownBlockType _block;
}

+ (id)dispatchScheduler:(id)arg1 frequency:(double)arg2 queue:(id)arg3 block:(CDUnknownBlockType)arg4;
@property(readonly, retain) CDUnknownBlockType block; // @synthesize block=_block;
@property double frequency; // @synthesize frequency=_frequency;
@property(copy) NSString *name; // @synthesize name=_name;
@property(readonly, retain) NSObject<OS_dispatch_group> *executingGroup; // @synthesize executingGroup=_executingGroup;
@property(readonly, retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, retain) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
@property(readonly) unsigned long long nextTime; // @synthesize nextTime=_nextTime;
@property(readonly) unsigned long long runCount; // @synthesize runCount=_runCount;
- (void).cxx_destruct;
- (id)nextRunTimeString;
- (void)waitUntilComplete;
- (void)suspend;
- (void)resume;
- (void)reset;
- (void)updateFrequency:(double)arg1;
- (void)_doIt;
- (void)doIt;
- (BOOL)scheduleAt:(id)arg1;
- (BOOL)scheduleNext:(double)arg1;
- (id)init:(id)arg1 frequency:(double)arg2 queue:(id)arg3 block:(CDUnknownBlockType)arg4;

@end

