//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAReceiver.h"

@class UAUserActivityClientProcessesController;

@interface UALocalItemReceiver : UAReceiver
{
    UAUserActivityClientProcessesController *_controller;
}

@property(readonly, retain) UAUserActivityClientProcessesController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)statusString;
- (id)receivedItems;
- (BOOL)receiving;
- (id)initWithManager:(id)arg1 controller:(id)arg2;

@end

