//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAAdvertiser.h"

@class NSFileHandle, NSString;

@interface UALoggingAdvertiser : UAAdvertiser
{
    NSFileHandle *_outputFile;
    NSString *_logFileDirectoryPath;
    NSString *_logFilePath;
}

@property(retain) NSString *logFilePath; // @synthesize logFilePath=_logFilePath;
@property(retain) NSString *logFileDirectoryPath; // @synthesize logFileDirectoryPath=_logFileDirectoryPath;
@property(retain) NSFileHandle *outputFile; // @synthesize outputFile=_outputFile;
- (void).cxx_destruct;
- (void)log:(int)arg1 format:(id)arg2;
- (void)log:(int)arg1 format:(id)arg2 args:(struct __va_list_tag [1])arg3;
- (BOOL)shouldLog:(int)arg1;
- (BOOL)suspend;
- (BOOL)resume;
- (BOOL)active;
- (id)statusString;
- (void)logItem:(id)arg1;
- (void)setAdvertisableItems:(id)arg1;
- (id)advertisableItems;
- (id)initWithManager:(id)arg1;

@end

