//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UAActivityReplay;

@interface UAMockActivityScanner : NSObject
{
    id <SFActivityScannerDelegate> _delegate;
    UAActivityReplay *_controller;
}

@property(retain) UAActivityReplay *controller; // @synthesize controller=_controller;
@property id <SFActivityScannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)activityPayloadFromDevice:(id)arg1 forAdvertisementPayload:(id)arg2 command:(id)arg3 timeout:(long long)arg4 withCompletionHandler:(CDUnknownBlockType)arg5;
- (id)initWithController:(id)arg1;

@end

