//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UAActivityReplay;

@interface UAMockActivityAdvertiser : NSObject
{
    id <SFActivityAdvertiserDelegate> _delegate;
    UAActivityReplay *_controller;
}

@property(retain) UAActivityReplay *controller; // @synthesize controller=_controller;
@property id <SFActivityAdvertiserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)fetchLoginIDWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchPeerForUUID:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)fetchSFPeerDevicesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)advertiseAdvertisementPayload:(id)arg1 options:(id)arg2;
- (id)initWithController:(id)arg1;

@end

