//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

#import "NSNetServiceBrowserDelegate.h"
#import "NSNetServiceDelegate.h"

@class NSNetService, NSNetServiceBrowser, NSString;

@interface UANetworkReplayRendevousHandler : UACornerActionManagerHandler <NSNetServiceDelegate, NSNetServiceBrowserDelegate>
{
    NSString *name;
    NSNetServiceBrowser *_browserLookup;
    NSString *_type;
    NSString *_domain;
    NSNetService *_listeningService;
}

@property(retain) NSNetService *listeningService; // @synthesize listeningService=_listeningService;
@property(copy) NSString *domain; // @synthesize domain=_domain;
@property(copy) NSString *type; // @synthesize type=_type;
@property(retain) NSNetServiceBrowser *browserLookup; // @synthesize browserLookup=_browserLookup;
@property(copy) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (void)netService:(id)arg1 didAcceptConnectionWithInputStream:(id)arg2 outputStream:(id)arg3;
- (void)netServiceDidStop:(id)arg1;
- (void)netService:(id)arg1 didNotResolve:(id)arg2;
- (void)netServiceDidResolveAddress:(id)arg1;
- (void)netServiceWillResolve:(id)arg1;
- (void)netService:(id)arg1 didNotPublish:(id)arg2;
- (void)netServiceDidPublish:(id)arg1;
- (void)netServiceWillPublish:(id)arg1;
- (BOOL)listenForIncomingConnections:(id)arg1 port:(int)arg2 type:(id)arg3;
- (void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(BOOL)arg3;
- (id)statusString;
- (BOOL)resume;
- (BOOL)suspend;
- (BOOL)scanForPeersOfType:(id)arg1 domain:(id)arg2;
- (void)dealloc;
- (id)initWithManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

