//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAActivityReplay.h"

#import "NSStreamDelegate.h"

@class NSInputStream, NSMutableData, NSOutputStream, NSString, NSUUID;

@interface UANetworkReplayController : UAActivityReplay <NSStreamDelegate>
{
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    NSMutableData *_readBuffer;
    NSMutableData *_writeBuffer;
    NSString *_peerName;
    NSUUID *_peerUUID;
}

+ (BOOL)createConnection:(id)arg1 host:(id)arg2 port:(long long)arg3;
@property(copy) NSUUID *peerUUID; // @synthesize peerUUID=_peerUUID;
@property(copy) NSString *peerName; // @synthesize peerName=_peerName;
@property(retain) NSMutableData *writeBuffer; // @synthesize writeBuffer=_writeBuffer;
@property(retain) NSMutableData *readBuffer; // @synthesize readBuffer=_readBuffer;
@property(retain) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain) NSInputStream *inputStream; // @synthesize inputStream=_inputStream;
- (void).cxx_destruct;
- (BOOL)terminate;
- (id)statusString;
- (BOOL)sendResponse:(id)arg1;
- (BOOL)processCommand:(id)arg1;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (id)initWithManager:(id)arg1 service:(id)arg2;
- (id)initWithManager:(id)arg1 inputStream:(id)arg2 outputStream:(id)arg3 name:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

