//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SFPeerDevice, UAPairedSFActivityScanner;

@interface UAPairedSFActivityAdvertiser : NSObject
{
    UAPairedSFActivityScanner *_pairedScanner;
    id <SFActivityAdvertiserDelegate> _delegate;
    SFPeerDevice *_peer;
}

@property(readonly, copy) SFPeerDevice *peer; // @synthesize peer=_peer;
@property id <SFActivityAdvertiserDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) UAPairedSFActivityScanner *pairedScanner; // @synthesize pairedScanner=_pairedScanner;
- (void).cxx_destruct;
- (void)payloadRequestFromPeer:(id)arg1 advertisementPayload:(id)arg2 command:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)fetchLoginIDWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)fetchPeerForUUID:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)fetchSFPeerDevicesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)advertiseAdvertisementPayload:(id)arg1 options:(id)arg2;
- (id)initWithDelegate:(id)arg1;

@end

