//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAClientController.h"

@class NSMutableArray, UAPingController;

@interface UAPingClient : UAClientController
{
    NSMutableArray *_items;
    BOOL _hasBeenUsedAtLeastOnce;
    UAPingController *_controller;
}

@property BOOL hasBeenUsedAtLeastOnce; // @synthesize hasBeenUsedAtLeastOnce=_hasBeenUsedAtLeastOnce;
@property(readonly, retain) UAPingController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)statusString;
- (long long)priority;
- (BOOL)active;
- (void)removeItem:(id)arg1;
- (void)pushItem:(id)arg1;
- (id)eligibleAdvertiseableItemsInOrder;
- (id)items;
- (id)initWithController:(id)arg1;

@end

