//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAUserActivityInfo.h"

@interface UAPingUserActivityInfo : UAUserActivityInfo
{
    CDUnknownBlockType _wasContinuedBlock;
}

@property(copy) CDUnknownBlockType wasContinuedBlock; // @synthesize wasContinuedBlock=_wasContinuedBlock;
- (void).cxx_destruct;
- (id)statusString;
- (id)initFromPing:(id)arg1;
- (id)initWithPayloadSize:(unsigned long long)arg1;

@end

