//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAActivityNotifier.h"

@class NSMutableSet;

@interface UAPingNotifier : UAActivityNotifier
{
    NSMutableSet *_pongItems;
    long long _pongCount;
}

@property long long pongCount; // @synthesize pongCount=_pongCount;
@property(readonly, copy) NSMutableSet *pongItems; // @synthesize pongItems=_pongItems;
- (void).cxx_destruct;
- (id)statusString;
- (void)setItems:(id)arg1;
- (id)items;
- (BOOL)active;
- (id)initWithManager:(id)arg1;

@end

