//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

@class UAPingClient, UAPingNotifier;

@interface UAPingController : UACornerActionManagerHandler
{
    UAPingClient *_client;
    UAPingNotifier *_notifier;
}

@property(readonly, retain) UAPingNotifier *notifier; // @synthesize notifier=_notifier;
@property(readonly, retain) UAPingClient *client; // @synthesize client=_client;
- (void).cxx_destruct;
- (BOOL)terminate;
- (BOOL)suspend;
- (BOOL)resume;
- (BOOL)active;
- (id)initWithManager:(id)arg1 name:(id)arg2;

@end

