//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAClientController.h"

@class UAUserActivityInfo;

@interface UAReplayClientController : UAClientController
{
    UAUserActivityInfo *_item;
}

@property(retain) UAUserActivityInfo *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (id)statusString;
- (id)userActivityInfoForUUID:(id)arg1;
- (id)eligibleAdvertiseableItemsInOrder;
- (id)items;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1;
- (void)dealloc;
- (id)initWithManager:(id)arg1;

@end

