//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class NSFileHandle, NSInputStream, NSMutableData, NSOutputStream, NSProgress, NSSet, NSString, UASharedPasteboardInfoWrapper;

@interface UASharedPasteboardInputStreamManager : NSObject <NSStreamDelegate>
{
    BOOL _receivedDelem;
    NSInputStream *_stream;
    NSOutputStream *_outStream;
    NSFileHandle *_file;
    NSProgress *_progress;
    CDUnknownBlockType _handler;
    NSSet *_typesToReceive;
    UASharedPasteboardInfoWrapper *_pbwrapper;
    NSMutableData *_receivedData;
    unsigned long long _streamStartTime;
    unsigned long long _timeRemaining;
    long long _bytesReceived;
    long long _expectedLength;
    unsigned long long _state;
}

@property BOOL receivedDelem; // @synthesize receivedDelem=_receivedDelem;
@property unsigned long long state; // @synthesize state=_state;
@property long long expectedLength; // @synthesize expectedLength=_expectedLength;
@property long long bytesReceived; // @synthesize bytesReceived=_bytesReceived;
@property unsigned long long timeRemaining; // @synthesize timeRemaining=_timeRemaining;
@property unsigned long long streamStartTime; // @synthesize streamStartTime=_streamStartTime;
@property(retain) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain) UASharedPasteboardInfoWrapper *pbwrapper; // @synthesize pbwrapper=_pbwrapper;
@property(retain) NSSet *typesToReceive; // @synthesize typesToReceive=_typesToReceive;
@property(copy) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain) NSProgress *progress; // @synthesize progress=_progress;
@property(retain) NSFileHandle *file; // @synthesize file=_file;
@property(retain) NSOutputStream *outStream; // @synthesize outStream=_outStream;
@property(retain) NSInputStream *stream; // @synthesize stream=_stream;
- (void).cxx_destruct;
- (unsigned long long)absoluteToNSec:(unsigned long long)arg1;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)streamDoneWithInfo:(id)arg1 error:(id)arg2;
- (void)cancel;
- (void)receiveTypes:(id)arg1 withProgress:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithInputStream:(id)arg1 outputStream:(id)arg2 dataFile:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

