//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAReceiver.h"

#import "SFActivityScannerDelegate.h"

@class NSMutableSet, NSSet, NSString, NSTimer, SFPeerDevice, UADispatchScheduler;

@interface UASharingReceiver : UAReceiver <SFActivityScannerDelegate>
{
    NSMutableSet *_sfActivityScanners;
    NSMutableSet *_receivedItems;
    NSMutableSet *_activeDevices;
    BOOL _forceScanning;
    UADispatchScheduler *_periodicCleanup;
    SFPeerDevice *_lastSeenPasteboardDevice;
    long long _lastSeenPasteboardVersionBit;
    NSTimer *_remotePboardTimer;
}

@property(retain) NSTimer *remotePboardTimer; // @synthesize remotePboardTimer=_remotePboardTimer;
@property long long lastSeenPasteboardVersionBit; // @synthesize lastSeenPasteboardVersionBit=_lastSeenPasteboardVersionBit;
@property(retain) SFPeerDevice *lastSeenPasteboardDevice; // @synthesize lastSeenPasteboardDevice=_lastSeenPasteboardDevice;
@property(readonly, retain) UADispatchScheduler *periodicCleanup; // @synthesize periodicCleanup=_periodicCleanup;
@property BOOL forceScanning; // @synthesize forceScanning=_forceScanning;
- (void).cxx_destruct;
- (void)clearRemotePasteboardAvalible:(id)arg1;
- (BOOL)terminate;
- (id)statusString;
- (void)receiveAdvertisement:(id)arg1 scanner:(id)arg2;
- (void)activityScanner:(id)arg1 receivedAdvertisement:(id)arg2;
- (id)sharingBTLESuggestedItemForAdvertisementPayload:(id)arg1 forDevice:(id)arg2;
- (void)periodicCleanupFunc;
- (void)removeAllFromDevice:(id)arg1;
- (BOOL)removeItem:(id)arg1;
- (BOOL)addItem:(id)arg1;
- (BOOL)_addItem:(id)arg1;
- (void)lostDeviceWithUUID:(id)arg1;
- (void)lostDevice:(id)arg1;
- (void)activityScanner:(id)arg1 lostDeviceWithDevice:(id)arg2;
- (void)foundDevice:(id)arg1;
- (void)activityScanner:(id)arg1 foundDeviceWithDevice:(id)arg2;
- (BOOL)resume;
- (BOOL)suspend;
- (id)sfActivityScanner;
- (BOOL)removeSFActivityScanner:(id)arg1;
- (BOOL)addSFActivityScanner:(id)arg1;
@property(readonly, copy) NSSet *sfActivityScanners;
- (BOOL)active;
@property(readonly, retain) NSSet *activeDevices;
- (id)receivedItems;
- (void)setScanningForTypes:(id)arg1;
- (BOOL)receiving;
- (id)initWithManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

