//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface UASharedPasteboardDataManager : NSObject
{
    NSString *_currentLocalBlobPath;
    NSString *_currentRemoteBlobPath;
    NSMutableDictionary *_tmpArchiveWriteFiles;
    NSMutableDictionary *_lockTokens;
}

+ (id)sharedInstance;
@property(retain) NSMutableDictionary *lockTokens; // @synthesize lockTokens=_lockTokens;
@property(retain) NSMutableDictionary *tmpArchiveWriteFiles; // @synthesize tmpArchiveWriteFiles=_tmpArchiveWriteFiles;
@property(retain) NSString *currentRemoteBlobPath; // @synthesize currentRemoteBlobPath=_currentRemoteBlobPath;
@property(retain) NSString *currentLocalBlobPath; // @synthesize currentLocalBlobPath=_currentLocalBlobPath;
- (void).cxx_destruct;
- (void)cleanupItemsDir;
- (void)cleanupArchiveDir;
- (void)cleanupForItem:(id)arg1;
- (void)releaseAllLocks;
- (void)releaseLockForItem:(id)arg1;
- (void)obtainLockForItem:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)writeArchiveData:(id)arg1 forItem:(id)arg2;
- (BOOL)createTmpArchiveFileWithUUID:(id)arg1;
- (id)readHandleForArchiveWithUUID:(id)arg1;
- (id)fileURLForArchiveWithUUID:(id)arg1;
- (id)fileURLForPasteboardItem:(id)arg1;
- (id)subDirForItem:(id)arg1;
- (id)remotePasteboardBlobForReading;
- (id)createFileForRemotePasteboardBlob;
- (id)localPasteboardBlobForReading;
- (id)createFileForLocalPasteboardBlob;
- (id)createFolderAtPath:(id)arg1;
- (BOOL)directoryExistsAtPath:(id)arg1;
- (id)createFileForUUID:(id)arg1 inSubFolder:(id)arg2;
- (id)createFileForUUID:(id)arg1;
- (BOOL)fileExistsForUUID:(id)arg1 inSubFolder:(id)arg2;
- (id)createSharedDataDirectory;
- (id)sharedDataPath;
- (id)init;

@end

