//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, NSUUID;

@protocol UASharedPasteboardProgressUIProtocol
- (void)endProgressForUUID:(NSUUID *)arg1 didFail:(BOOL)arg2;
- (void)showProgressForUUID:(NSUUID *)arg1 fromDevice:(NSString *)arg2 deviceModel:(NSString *)arg3 deviceColor:(NSString *)arg4;
@end

