//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import<Foundation/Foundation.h>

//#import "NSObject.h"
//
//#import "NSSecureCoding.h"

@class NSData, NSError, UASharedPasteboardInfo;

@interface UASharedPasteboardInfoWrapper : NSObject <NSSecureCoding>
{
    UASharedPasteboardInfo *_pbinfo;
    NSData *_extraData;
    long long _extraDataType;
    NSError *_error;
    long long _protocolVersion;
}

+ (BOOL)supportsSecureCoding;
@property long long protocolVersion; // @synthesize protocolVersion=_protocolVersion;
@property(retain) NSError *error; // @synthesize error=_error;
@property long long extraDataType; // @synthesize extraDataType=_extraDataType;
@property(retain) NSData *extraData; // @synthesize extraData=_extraData;
@property(retain) UASharedPasteboardInfo *pbinfo; // @synthesize pbinfo=_pbinfo;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

