//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

#import "UAActivityNotifierProtocol.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSSet, NSString, SFPeerDevice, UASimulatorAdvertisementCreator, UASimulatorAdvertiser, UASimulatorController, UASimulatorReceiver;

@interface UASimulator : UACornerActionManagerHandler <UAActivityNotifierProtocol>
{
    unsigned int _pairedClientPort;
    int _notifyToken;
    NSMutableSet *_notifiedItems;
    BOOL _activitiesShouldCrossover;
    unsigned int _commandPort;
    int _simulatorPid;
    UASimulatorController *_controller;
    SFPeerDevice *_ourDevice;
    SFPeerDevice *_peeredDevice;
    UASimulatorAdvertiser *_advertiser;
    UASimulatorReceiver *_receiver;
    UASimulatorAdvertisementCreator *_creator;
    NSObject<OS_dispatch_queue> *_dispatchQ;
    void *_frontNotificationID;
    NSString *_bootstrapName;
}

+ (id)simulatorWithController:(id)arg1 parentSimulatorPortName:(id)arg2;
+ (id)simulatorWithController:(id)arg1 pairedPort:(unsigned int)arg2 childSimPid:(int)arg3 childVersion:(unsigned long long)arg4;
@property(readonly, copy) NSString *bootstrapName; // @synthesize bootstrapName=_bootstrapName;
@property void *frontNotificationID; // @synthesize frontNotificationID=_frontNotificationID;
@property int simulatorPid; // @synthesize simulatorPid=_simulatorPid;
@property(readonly, retain) NSObject<OS_dispatch_queue> *dispatchQ; // @synthesize dispatchQ=_dispatchQ;
@property(readonly) unsigned int commandPort; // @synthesize commandPort=_commandPort;
@property(readonly) BOOL activitiesShouldCrossover; // @synthesize activitiesShouldCrossover=_activitiesShouldCrossover;
@property(readonly, retain) UASimulatorAdvertisementCreator *creator; // @synthesize creator=_creator;
@property(readonly, retain) UASimulatorReceiver *receiver; // @synthesize receiver=_receiver;
@property(readonly, retain) UASimulatorAdvertiser *advertiser; // @synthesize advertiser=_advertiser;
@property(retain) SFPeerDevice *peeredDevice; // @synthesize peeredDevice=_peeredDevice;
@property(retain) SFPeerDevice *ourDevice; // @synthesize ourDevice=_ourDevice;
@property(readonly, retain) UASimulatorController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)statusString;
- (BOOL)terminate;
- (BOOL)suspend;
- (BOOL)resume;
- (void)setSimulatorInFront:(BOOL)arg1;
- (BOOL)active;
@property(copy) NSSet *notifiedItems;
@property(readonly) unsigned int pairedClientPort; // @dynamic pairedClientPort;
- (BOOL)reconnectToParentSimulator;
- (void)dealloc;
- (id)initWithController:(id)arg1;

@end

