//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAClientController.h"

@class UASimulator;

@interface UASimulatorAdvertisementCreator : UAClientController
{
    UASimulator *_simulator;
}

@property(readonly, retain) UASimulator *simulator; // @synthesize simulator=_simulator;
- (void).cxx_destruct;
- (id)statusString;
- (BOOL)active;
- (long long)priority;
- (id)eligibleAdvertiseableItemsInOrder;
- (id)items;
- (id)initWithManager:(id)arg1 simulator:(id)arg2;

@end

