//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSSet, SFPeerDevice;

@interface UASimulatorController : UACornerActionManagerHandler
{
    NSMutableSet *_simulators;
    unsigned int _simulatorPort;
    NSObject<OS_dispatch_queue> *_dispatchQ;
    SFPeerDevice *_ourPeerDevice;
}

@property(retain) SFPeerDevice *ourPeerDevice; // @synthesize ourPeerDevice=_ourPeerDevice;
@property unsigned int simulatorPort; // @synthesize simulatorPort=_simulatorPort;
@property(retain) NSObject<OS_dispatch_queue> *dispatchQ; // @synthesize dispatchQ=_dispatchQ;
- (void).cxx_destruct;
- (id)simulatorStatus;
- (id)statusString;
- (BOOL)terminate;
- (BOOL)active;
- (void)removeSimulator:(id)arg1;
- (void)addSimulator:(id)arg1;
@property(readonly, retain) NSSet *simulators;
- (id)initWithManager:(id)arg1;

@end

