//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class NSData, NSError, NSInputStream, NSMutableArray, NSMutableData, NSOutputStream, NSString;

@interface UAStreamHandler : NSObject <NSStreamDelegate>
{
    BOOL _shouldStop;
    BOOL _shouldTryWrite;
    unsigned int _inMessageLength;
    NSInputStream *_inStream;
    NSOutputStream *_outStream;
    NSError *_streamError;
    id <UAStreamHandlerDelegate> _delegate;
    NSMutableData *_outputStreamData;
    long long _byteIndex;
    long long _outMessageTag;
    NSMutableData *_outMessage;
    NSMutableArray *_messageQueue;
    long long _bytesRead;
    long long _inMessageTag;
    NSData *_inMessage;
    NSMutableData *_inData;
    unsigned long long _inputState;
    unsigned long long _outputMode;
    long long _totalBytesSent;
    long long _totalBytesReceived;
}

@property BOOL shouldTryWrite; // @synthesize shouldTryWrite=_shouldTryWrite;
@property BOOL shouldStop; // @synthesize shouldStop=_shouldStop;
@property long long totalBytesReceived; // @synthesize totalBytesReceived=_totalBytesReceived;
@property long long totalBytesSent; // @synthesize totalBytesSent=_totalBytesSent;
@property unsigned long long outputMode; // @synthesize outputMode=_outputMode;
@property unsigned long long inputState; // @synthesize inputState=_inputState;
@property(retain) NSMutableData *inData; // @synthesize inData=_inData;
@property(retain) NSData *inMessage; // @synthesize inMessage=_inMessage;
@property unsigned int inMessageLength; // @synthesize inMessageLength=_inMessageLength;
@property long long inMessageTag; // @synthesize inMessageTag=_inMessageTag;
@property long long bytesRead; // @synthesize bytesRead=_bytesRead;
@property(retain) NSMutableArray *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(retain) NSMutableData *outMessage; // @synthesize outMessage=_outMessage;
@property long long outMessageTag; // @synthesize outMessageTag=_outMessageTag;
@property long long byteIndex; // @synthesize byteIndex=_byteIndex;
@property(retain) NSMutableData *outputStreamData; // @synthesize outputStreamData=_outputStreamData;
@property __weak id <UAStreamHandlerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSError *streamError; // @synthesize streamError=_streamError;
@property(retain) NSOutputStream *outStream; // @synthesize outStream=_outStream;
@property(retain) NSInputStream *inStream; // @synthesize inStream=_inStream;
- (void).cxx_destruct;
- (id)trimFirstBytes:(unsigned long long)arg1 ofData:(id)arg2;
- (long long)tryWriteMessage;
- (long long)tryWriteRawData;
- (long long)handleSpaceAvalible;
- (void)handleMessageRead;
- (BOOL)dataHasMessage:(id)arg1;
- (void)processHeader;
- (void)handleBytesAvailable;
- (void)handleOpenCompleted;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (BOOL)writeMessage:(id)arg1 tag:(long long)arg2;
- (BOOL)writeRawData:(id)arg1;
- (void)_stop;
- (void)tryStop;
- (void)stop;
- (void)start;
- (long long)queueCount;
- (id)initWithInputStream:(id)arg1 outputStream:(id)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

