//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, UAStreamHandler;

@protocol UAStreamHandlerDelegate <NSObject>
- (void)streams:(UAStreamHandler *)arg1 didReadMessage:(NSData *)arg2 withTag:(long long)arg3;

@optional
- (void)streamsDidWriteRawDataBuffer:(UAStreamHandler *)arg1;
- (void)streams:(UAStreamHandler *)arg1 didReadRawData:(NSData *)arg2;
- (void)streamsDidClose:(UAStreamHandler *)arg1 withError:(NSError *)arg2;
- (void)streams:(UAStreamHandler *)arg1 didWriteMessageWithTag:(long long)arg2;
@end

