//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UACornerActionManagerHandler.h"

#import "UAUserActivityClientProtocol.h"

@class NSArray, NSDate, NSMutableDictionary, NSMutableSet, NSString, NSUUID, NSXPCConnection, UAAuditToken, UACornerActionManager, UAUserActivityAdvertisableItem, UAUserActivityClientProcessesController;

@interface UAUserActivityClientProcess : UACornerActionManagerHandler <UAUserActivityClientProtocol>
{
    NSMutableSet *_pendingResumeActivityUUIDs;
    void *_lsNotificationID;
    BOOL _clientIsSandboxed;
    unsigned char _allowedToAccessAnyItem;
    BOOL _frontmost;
    BOOL _allowedToUseLSAlwaysEligible;
    BOOL _allowedToUseEligibleEvenWhenInBackground;
    BOOL _allowedToUseLSAlwaysPick;
    BOOL _allowedToUseUAAlwaysAdvertise;
    BOOL _allowedToGetCurrentActivityInfo;
    NSXPCConnection *_connection;
    UACornerActionManager *_manager;
    UAAuditToken *_auditToken;
    NSString *_bundleIdentifier;
    NSString *_applicationIdentifier;
    NSString *_teamID;
    NSMutableSet *_dirtyUUIDs;
    UAUserActivityClientProcessesController *_controller;
    UAUserActivityAdvertisableItem *_currentAdvertisableActivity;
    NSDate *_lastFrontTime;
    NSMutableDictionary *_userActivityAdvertisableItemsByUUID;
}

@property(retain) NSMutableDictionary *userActivityAdvertisableItemsByUUID; // @synthesize userActivityAdvertisableItemsByUUID=_userActivityAdvertisableItemsByUUID;
@property(copy) NSDate *lastFrontTime; // @synthesize lastFrontTime=_lastFrontTime;
@property BOOL allowedToGetCurrentActivityInfo; // @synthesize allowedToGetCurrentActivityInfo=_allowedToGetCurrentActivityInfo;
@property BOOL allowedToUseUAAlwaysAdvertise; // @synthesize allowedToUseUAAlwaysAdvertise=_allowedToUseUAAlwaysAdvertise;
@property BOOL allowedToUseLSAlwaysPick; // @synthesize allowedToUseLSAlwaysPick=_allowedToUseLSAlwaysPick;
@property BOOL allowedToUseEligibleEvenWhenInBackground; // @synthesize allowedToUseEligibleEvenWhenInBackground=_allowedToUseEligibleEvenWhenInBackground;
@property BOOL allowedToUseLSAlwaysEligible; // @synthesize allowedToUseLSAlwaysEligible=_allowedToUseLSAlwaysEligible;
@property BOOL frontmost; // @synthesize frontmost=_frontmost;
@property(readonly, retain) UAUserActivityAdvertisableItem *currentAdvertisableActivity; // @synthesize currentAdvertisableActivity=_currentAdvertisableActivity;
@property(readonly, retain) UAUserActivityClientProcessesController *controller; // @synthesize controller=_controller;
@property(readonly, copy) NSMutableSet *dirtyUUIDs; // @synthesize dirtyUUIDs=_dirtyUUIDs;
@property unsigned char allowedToAccessAnyItem; // @synthesize allowedToAccessAnyItem=_allowedToAccessAnyItem;
@property(copy) NSString *teamID; // @synthesize teamID=_teamID;
@property(readonly, copy) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
@property(readonly, copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property BOOL clientIsSandboxed; // @synthesize clientIsSandboxed=_clientIsSandboxed;
@property(readonly, retain) UAAuditToken *auditToken; // @synthesize auditToken=_auditToken;
@property __weak UACornerActionManager *manager; // @synthesize manager=_manager;
@property(readonly) __weak NSXPCConnection *connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)debugStateChanged:(id)arg1;
- (id)statusString;
- (void)doRegisterAsProxyApplicationForPid:(int)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)doMarkUserActivityAsDirty:(id)arg1 forceImmediate:(BOOL)arg2 webpageURL:(id)arg3 expiration:(id)arg4 hasiCloudDocument:(BOOL)arg5 hasUnsynchronizediCloudDoc:(BOOL)arg6;
- (void)doUpdateUserActivityWithUUID:(id)arg1 setActive:(BOOL)arg2;
- (void)doUpdateUserActivityInfo:(id)arg1 makeCurrent:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)doFetchUserActivityInfoWithUUID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doGetLoggingFileForClient:(id)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)doDetermineIfUserActivityIsCurrent:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doGetCurrentUserActivityInfo:(CDUnknownBlockType)arg1;
- (void)doPinUserActivityInfo:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)doRemoveDynamicUserActivity:(id)arg1 matching:(id)arg2;
- (void)doAddDynamicUserActivity:(id)arg1 matching:(id)arg2;
- (void)doDeleteUserActivityWithUUID:(id)arg1;
- (void)doInitializeWithClientVersion:(long long)arg1 clientInfo:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(readonly, copy) NSString *description;
- (BOOL)didResumeUserActivityWithUUID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)askSourceProcessToUpdateActivityWithUUID:(id)arg1 evenIfClean:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (BOOL)isDirtyActivityWithUUID:(id)arg1;
- (BOOL)isEligibleToAlwaysAdvertiseWithUUID:(id)arg1;
- (BOOL)isEligibleToAdvertiseWithUUID:(id)arg1;
- (BOOL)removeUserActivityAdvertiseableItemByUUID:(id)arg1;
- (void)removeUserActivity:(id)arg1;
- (void)addUserActivity:(id)arg1;
@property(readonly) NSArray *uniqueIdentifiers;
- (id)userActivityAdvertisableItemByUUID:(id)arg1;
- (void)invalidate;
- (id)initWithController:(id)arg1 connection:(id)arg2;

// Remaining properties
@property(readonly, copy) NSUUID *currentActivityUUID; // @dynamic currentActivityUUID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

