//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSUserDefaults;

@interface UAUserActivityDefaults : NSObject
{
    NSUserDefaults *_userDefaults;
}

+ (id)sharedDefaults;
@property(readonly, retain) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void).cxx_destruct;
- (void)setDefault:(id)arg1 value:(id)arg2;
- (id)defaults:(BOOL)arg1;
- (id)statusString;
- (BOOL)ignoreLostDevice;
- (BOOL)shouldIgnoreBluetoothDisabled;
- (double)payloadFetchResponseDelay;
- (double)handoffPayloadRequestTimout;
- (double)pasteboardPasteRequestTimeout;
- (double)pasteboardTypeRequestTimeout;
- (double)pasteboardHideUIDelay;
- (double)pasteboardUIMinimumDurration;
- (double)pasteboardShowUIDelay;
- (double)pasteboardUITimeRemainingDelay;
- (long long)pasteboardEmbeddedPayloadSizeLimitInBytes;
- (void)setLocalPasteboardReflection:(BOOL)arg1;
- (BOOL)localPasteboardRefection;
- (double)remotePasteboardAvailableTimeout;
- (double)localPasteboardAvalibilityClearedTimeout;
- (double)localPasteboardAvalibilityTimeout;
@property BOOL enableSharingFramework;
- (BOOL)debugIgnoreAppsUsedForDevelopment;
- (BOOL)debugCrossoverAllActivities;
- (BOOL)debugEnablePrefetch;
- (BOOL)debugEnablePinging;
- (BOOL)debugReadvertiseImmediately;
- (BOOL)dontSendActivityTitle;
- (BOOL)debugForceOldPayloadEncoder;
- (BOOL)debugForceNewPayloadEncoder;
- (long long)debugUserActivityTimeOffset;
- (long long)debugValidateSampleResponseMaximumActivityPayloadSizeInBytes;
- (long long)debugValidateSampleResponseMinimumActivityPayloadSizeInBytes;
- (double)debugValidateRetryPayloadFetchFailureInterval;
- (double)debugAdditionalPayloadReceiveTimeInterval;
- (double)debugValidatePayloadFetchTimeInterval;
- (double)maximumAdvertisementsTimeInterval;
- (long long)maximumAdvertisementsPerTimeInterval;
- (double)minimumIntervalBetweenAdvertisements;
- (long long)activityPayloadWarningSizeInBytes;
- (int)networkControlListenerPort;
- (id)rendevousPairingType;
- (BOOL)enableAutomaticRendevousPairing;
- (BOOL)enableNetworkControlListener;
- (long long)maximumActivityPayloadSizeInBytes;
- (double)maximumTimeoutToWaitForClientProcessToUpdateActivityInformation;
- (double)activePayloadUpdateInterval;
- (double)receivedBTLEItemTimeToLiveAfterDeviceLostIfPayloadIsQueued;
- (double)cornerActionItemMaximumTimeForBTLEItemToLive;
- (double)cornerActionItemAdditionalTimeToLiveAfterValidIntervalExpires;
- (double)cornerActionItemTimeout;
- (double)intervalToAskClientWithUnsynchronizedDocumentsToUpdate;
- (double)advertisedItemWhichIsWebBrowserIntervalToRememberEarlierActivities;
- (double)bestAppSuggestionSupressionIntervalForUnchangingItem;
- (double)cornerActionItemSupressionInterval;
- (double)maximumTimeoutAfterAdvertisingEndsThatActivityCanBeResumed;
- (double)systemIdleDelayBeforeRemovingAdvertisements;
- (double)screenDimDelayBeforeRemovingPasteboardAdvertisement;
- (double)screenDimDelayBeforeRemovingAdvertisements;
- (double)screenSaverDelayBeforeRemovingPasteboardAdvertisement;
- (double)screenSaverDelayToRemovingAdvertisements;
- (double)recentlyEligibleItemInterval;
- (double)minimumTimeToLiveAfterRemovingAdvertisement;
- (double)minimumTimeForAnAdvertisementToLive;
- (double)deviceLockDelayBeforeRemovingPasteboardAdvertisement;
- (double)deviceLockDelayBeforeRemovingHandoffAdvertisement;
- (double)userIdleInterval;
- (BOOL)loggingAdvertiserEnabled;
- (BOOL)activityBTLESharingEnabled;
- (BOOL)enableHandoffInPowerSaverMode;
- (BOOL)clipboardSharingEnabled;
- (BOOL)activityContinuationAllowed;
- (BOOL)activityReceivingAllowed;
- (BOOL)activityAdvertisingAllowed;
- (BOOL)isBatterySaverModeEnabled;
- (double)timeIntervalForKey:(id)arg1 default:(double)arg2;
- (long long)integerValueForKey:(id)arg1 default:(long long)arg2;
- (BOOL)boolValueForKey:(id)arg1 default:(BOOL)arg2;
- (id)cornerActionItemDefaults;
- (id)init;

@end

