//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAClientController.h"

#import "NSXPCListenerDelegate.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSSet, NSString, NSXPCListener, UALocalItemReceiver, UAUserActivityClientProcess;

@interface UAUserActivityClientProcessesController : UAClientController <NSXPCListenerDelegate>
{
    NSXPCListener *_activityManagerListener;
    NSMutableSet *_clients;
    NSMutableDictionary *_userActivityClientsByPID;
    NSMutableSet *_visibleUserActivityClients;
    NSMutableSet *_additionalUserActivityAdvertisableItems;
    NSMutableDictionary *_proxiedClients;
    void *_lsAppFrontmostNotifications;
    UALocalItemReceiver *_localReceiver;
    UAUserActivityClientProcess *_advertisingProcess;
}

@property(retain) UAUserActivityClientProcess *advertisingProcess; // @synthesize advertisingProcess=_advertisingProcess;
@property(retain) UALocalItemReceiver *localReceiver; // @synthesize localReceiver=_localReceiver;
@property(readonly, retain) NSMutableDictionary *proxiedClients; // @synthesize proxiedClients=_proxiedClients;
@property(readonly) void *lsAppFrontmostNotifications; // @synthesize lsAppFrontmostNotifications=_lsAppFrontmostNotifications;
- (void).cxx_destruct;
- (id)statusString;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)receiveLSNotification:(int)arg1 data:(id)arg2;
- (id)recentEligibleItemsInOrder:(double)arg1;
- (id)eligibleAdvertiseableItemsInOrder;
- (id)items;
- (BOOL)registerAsProxyApplication:(id)arg1 forPid:(int)arg2;
- (BOOL)clientIsVisible:(id)arg1;
- (void)makeClientFrontmost:(id)arg1;
- (void)removeClientActivityClient:(id)arg1;
- (BOOL)removeAdditionalUserActivityAdvertisableItems:(id)arg1;
- (BOOL)addAdditionalUserActivityAdvertisableItems:(id)arg1;
@property(readonly, copy) NSSet *additionalUserActivityAdvertisableItems;
- (id)userActivityClientForASN:(struct __LSASN *)arg1;
- (id)userActivityClientForPID:(int)arg1;
- (id)userActivityClientForUUID:(id)arg1;
@property(copy) NSSet *visibleUserActivityClients; // @dynamic visibleUserActivityClients;
@property(readonly, copy) NSArray *userActivityClients; // @dynamic userActivityClients;
- (id)userActivityInfoForUUID:(id)arg1;
- (BOOL)clientIsActive:(id)arg1;
- (void)addUserActivityClient:(id)arg1;
- (BOOL)resume;
- (BOOL)suspend;
- (void)dealloc;
- (id)initWithManager:(id)arg1 name:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

