//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UAAdvertisableItem.h"

@class UAUserActivityClientProcess;

@interface UAUserActivityAdvertisableItem : UAAdvertisableItem
{
    UAUserActivityClientProcess *_client;
}

@property __weak UAUserActivityClientProcess *client; // @synthesize client=_client;
- (void).cxx_destruct;
- (BOOL)wasResumedOnAnotherDeviceWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)requestPayloadWithCompletionHandlerEvenIfClean:(BOOL)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (BOOL)needsUpdateBeforeAdvertising;
- (BOOL)isDirty;
- (BOOL)eligibleToAlwaysAdvertise;
- (BOOL)eligibleToAdvertise;
- (BOOL)update:(id)arg1;
@property(readonly) BOOL eligibleInBackground;
- (BOOL)alwaysEligible;
- (long long)alwaysPickValue;
- (BOOL)alwaysPick;
- (void)setWebpageURL:(id)arg1;
- (id)webpageURL;
- (id)initWithUUID:(id)arg1 type:(unsigned long long)arg2 options:(id)arg3 client:(id)arg4;
- (id)initWithUserActivityInfo:(id)arg1 client:(id)arg2;

@end

