//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, NSUUID;

@interface UCArchiver : NSObject
{
    NSURL *_baseURL;
    NSString *_leaf;
    NSUUID *_uuid;
    void *_writer;
}

@property void *writer; // @synthesize writer=_writer;
@property(retain) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(retain) NSString *leaf; // @synthesize leaf=_leaf;
@property(retain) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void).cxx_destruct;
- (void)archiveURLWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithURL:(id)arg1 typeUUID:(id)arg2;

@end

