//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSFileHandle, NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString;

@interface UCFilePackager : NSObject
{
    long long _totalPacketCount;
    long long _tag;
    NSString *_uuid;
    id <UCFilePacketReceiver> _receiver;
    NSFileHandle *_file;
    NSDictionary *_options;
    long long _packetSize;
    long long _packetPreLoadCount;
    NSMutableArray *_queuedPackets;
    long long _nextPacketNumber;
    long long _nextPacketToDeliver;
    long long _currentPacketNumber;
    NSObject<OS_dispatch_queue> *_fetchQ;
    NSObject<OS_dispatch_semaphore> *_nextPacketReady;
}

@property(retain) NSObject<OS_dispatch_semaphore> *nextPacketReady; // @synthesize nextPacketReady=_nextPacketReady;
@property(retain) NSObject<OS_dispatch_queue> *fetchQ; // @synthesize fetchQ=_fetchQ;
@property long long currentPacketNumber; // @synthesize currentPacketNumber=_currentPacketNumber;
@property long long nextPacketToDeliver; // @synthesize nextPacketToDeliver=_nextPacketToDeliver;
@property long long nextPacketNumber; // @synthesize nextPacketNumber=_nextPacketNumber;
@property(retain) NSMutableArray *queuedPackets; // @synthesize queuedPackets=_queuedPackets;
@property long long packetPreLoadCount; // @synthesize packetPreLoadCount=_packetPreLoadCount;
@property long long packetSize; // @synthesize packetSize=_packetSize;
@property(retain) NSDictionary *options; // @synthesize options=_options;
@property(retain) NSFileHandle *file; // @synthesize file=_file;
@property __weak id <UCFilePacketReceiver> receiver; // @synthesize receiver=_receiver;
@property(retain) NSString *uuid; // @synthesize uuid=_uuid;
@property long long tag; // @synthesize tag=_tag;
@property long long totalPacketCount; // @synthesize totalPacketCount=_totalPacketCount;
- (void).cxx_destruct;
- (void)checkShouldFetch;
- (void)prepNextPacket;
- (BOOL)deliverNextPacket;
- (id)initWithFile:(id)arg1 fileSize:(long long)arg2 packetSize:(long long)arg3 options:(id)arg4 receiver:(id)arg5;

@end

