//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSMutableArray, NSObject<OS_dispatch_semaphore>, NSUUID, UASharedPasteboardDataRequester, UASharedPasteboardInfo;

@interface UCRemotePasteboardGeneration : NSObject
{
    BOOL _returnEarly;
    BOOL _dataRequested;
    UASharedPasteboardDataRequester *_dataRequester;
    UASharedPasteboardInfo *_pbInfo;
    unsigned long long _state;
    long long _streamProtocolVersion;
    NSUUID *_uuid;
    NSObject<OS_dispatch_semaphore> *_typeSem;
    NSMutableArray *_typeRespQueue;
    NSError *_error;
}

@property(retain) NSError *error; // @synthesize error=_error;
@property(retain) NSMutableArray *typeRespQueue; // @synthesize typeRespQueue=_typeRespQueue;
@property(retain) NSObject<OS_dispatch_semaphore> *typeSem; // @synthesize typeSem=_typeSem;
@property(retain) NSUUID *uuid; // @synthesize uuid=_uuid;
@property BOOL dataRequested; // @synthesize dataRequested=_dataRequested;
@property long long streamProtocolVersion; // @synthesize streamProtocolVersion=_streamProtocolVersion;
@property BOOL returnEarly; // @synthesize returnEarly=_returnEarly;
@property unsigned long long state; // @synthesize state=_state;
@property(retain) UASharedPasteboardInfo *pbInfo; // @synthesize pbInfo=_pbInfo;
@property(retain) UASharedPasteboardDataRequester *dataRequester; // @synthesize dataRequester=_dataRequester;
- (void).cxx_destruct;
- (void)requestRemotePasteboardData:(CDUnknownBlockType)arg1;
- (void)requestRemoteTypeInfo:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)updateState:(unsigned long long)arg1;
- (id)stateAsString;
- (id)initWithRequester:(id)arg1;

@end

