//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UAStreamHandlerDelegate.h"
#import "UCFilePacketReceiver.h"
#import "UCStreamCoder.h"

@class NSDictionary, NSFileHandle, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_semaphore>, NSProgress, NSString, UASharedPasteboardInfoWrapper, UAStreamHandler, UCFilePackager;

@interface UCStreamCoderV2 : NSObject <UAStreamHandlerDelegate, UCFilePacketReceiver, UCStreamCoder>
{
    BOOL _remoteHasFiles;
    BOOL _returnInfoEarly;
    UAStreamHandler *_streamHandler;
    long long _state;
    NSDictionary *_auxStateInfo;
    NSMutableArray *_objects;
    CDUnknownBlockType _infoRecvHandler;
    CDUnknownBlockType _fileRecvHandler;
    UASharedPasteboardInfoWrapper *_receivedInfo;
    NSFileHandle *_receivingDataFile;
    NSProgress *_progress;
    long long _bytesReceived;
    NSObject<OS_dispatch_semaphore> *_itemsLockedSem;
    NSMutableDictionary *_uuidItemMap;
    unsigned long long _streamStartTime;
    long long _expectedLength;
    CDUnknownBlockType _sendErrorHandler;
    UASharedPasteboardInfoWrapper *_sendingInfo;
    NSFileHandle *_sendingDataFile;
    UCFilePackager *_filePackager;
    NSMutableDictionary *_archivePackagers;
    NSMutableArray *_archiveQueue;
    NSMutableArray *_requestedArchives;
    long long _totalSendSize;
}

@property long long totalSendSize; // @synthesize totalSendSize=_totalSendSize;
@property(retain) NSMutableArray *requestedArchives; // @synthesize requestedArchives=_requestedArchives;
@property(retain) NSMutableArray *archiveQueue; // @synthesize archiveQueue=_archiveQueue;
@property(retain) NSMutableDictionary *archivePackagers; // @synthesize archivePackagers=_archivePackagers;
@property(retain) UCFilePackager *filePackager; // @synthesize filePackager=_filePackager;
@property(retain) NSFileHandle *sendingDataFile; // @synthesize sendingDataFile=_sendingDataFile;
@property(retain) UASharedPasteboardInfoWrapper *sendingInfo; // @synthesize sendingInfo=_sendingInfo;
@property(copy) CDUnknownBlockType sendErrorHandler; // @synthesize sendErrorHandler=_sendErrorHandler;
@property long long expectedLength; // @synthesize expectedLength=_expectedLength;
@property unsigned long long streamStartTime; // @synthesize streamStartTime=_streamStartTime;
@property(retain) NSMutableDictionary *uuidItemMap; // @synthesize uuidItemMap=_uuidItemMap;
@property(retain) NSObject<OS_dispatch_semaphore> *itemsLockedSem; // @synthesize itemsLockedSem=_itemsLockedSem;
@property BOOL returnInfoEarly; // @synthesize returnInfoEarly=_returnInfoEarly;
@property BOOL remoteHasFiles; // @synthesize remoteHasFiles=_remoteHasFiles;
@property long long bytesReceived; // @synthesize bytesReceived=_bytesReceived;
@property(retain) NSProgress *progress; // @synthesize progress=_progress;
@property(retain) NSFileHandle *receivingDataFile; // @synthesize receivingDataFile=_receivingDataFile;
@property(retain) UASharedPasteboardInfoWrapper *receivedInfo; // @synthesize receivedInfo=_receivedInfo;
@property(copy) CDUnknownBlockType fileRecvHandler; // @synthesize fileRecvHandler=_fileRecvHandler;
@property(copy) CDUnknownBlockType infoRecvHandler; // @synthesize infoRecvHandler=_infoRecvHandler;
@property(retain) NSMutableArray *objects; // @synthesize objects=_objects;
@property(retain) NSDictionary *auxStateInfo; // @synthesize auxStateInfo=_auxStateInfo;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain) UAStreamHandler *streamHandler; // @synthesize streamHandler=_streamHandler;
- (void).cxx_destruct;
- (id)fetchDataForType:(id)arg1;
- (id)unpackMessage:(id)arg1;
- (id)packMessage:(id)arg1;
- (void)filePackagerError:(id)arg1;
- (void)packager:(id)arg1 gotData:(id)arg2 forPacket:(long long)arg3;
- (void)sendCompletedWithError:(id)arg1;
- (void)sendPasteboard:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)calculateTimeRemaining;
- (void)processPasteboardInfo:(id)arg1;
- (void)removeReceivedItems:(id)arg1;
- (void)completedReceivingPasteboardWithError:(id)arg1;
- (void)receivedPasteboardInfo:(id)arg1 withError:(id)arg2;
- (void)cancelReceive;
- (void)receivePasteboardToFile:(id)arg1 withProgress:(id)arg2 infoRecievedHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4 returnInfoEarly:(BOOL)arg5;
- (void)sendTotalSendSize;
- (void)sendPasteboardDataResponse;
- (void)sendFileArchiveRequest;
- (void)sendPasteboardDataRequest;
- (void)sendPasteboardInfoResponse;
- (void)sendPasteboardInfoRequest;
- (void)handlePasteboardAuxInfoReceived:(id)arg1;
- (void)handlePasteboardFileResponse:(id)arg1;
- (void)handlePasteboardDataResponse:(id)arg1;
- (void)handlePasteboardInfoResponse:(id)arg1;
- (void)handlePasteboardFileRequest:(id)arg1;
- (void)handlePasteboardDataRequest:(id)arg1;
- (void)handlePasteboardInfoRequest:(id)arg1;
- (void)recvStop:(id)arg1;
- (void)sendStopWithError:(long long)arg1;
- (void)streams:(id)arg1 didWriteMessageWithTag:(long long)arg2;
- (void)streams:(id)arg1 didReadMessage:(id)arg2 withTag:(long long)arg3;
- (void)streamsDidClose:(id)arg1 withError:(id)arg2;
- (void)removeObject:(id)arg1;
- (void)storeObject:(id)arg1;
- (void)dealloc;
- (id)initWithInputStream:(id)arg1 outputStream:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

